#!/bin/sh
#
# chkconfig: 345 99 99
# description: Nextone Iserver startup script

BOOT_FILE='.boot'
BOOT_DIR='NarsAgentDirectory'
NARS_PID_FILE='nars.pid'
LOGPP_PID_FILE='logpp.pid'

test -d $BOOT_DIR || exit 0
STARTDIR=`pwd`
case "$1" in
	start)
		if [ -f "$BOOT_DIR/$BOOT_FILE" ]; then
			cd $BOOT_DIR
			if [ -f "$BOOT_DIR/$NARS_PID_FILE" ]; then
				rm -f $BOOT_DIR/$NARS_PID_FILE
			fi
			if [ -f "$BOOT_DIR/$LOGPP_PID_FILE" ]; then
				rm -f $BOOT_DIR/$LOGPP_PID_FILE
			fi
			./narsagent all start < /dev/null
			cd $STARTDIR
		fi
		;;
	stop)
		cd $BOOT_DIR
		./narsagent all stop < /dev/null
		cd $STARTDIR
		;;
	status)
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
		exit 1
esac

# append stuff for restarting 
test -d $BOOT_DIR || exit 0

exit 0
