#! /bin/sh

## This script simulates redhat's rc.local (Add commands at the end)

### BEGIN INIT INFO
# Provides: rclocal
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# X-UnitedLinux-Should-Start: $ALL
# Required-Stop:
# X-UnitedLinux-Should-Stop:
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Short-Description: Simulates rc.local
# Description: Simulates redhat's rc.local: contains
# commands to execute after system has booted (all services are already
# available)
### END INIT INFO

## Execute ony when service is started
case "$1" in
  start)
    ## commands will be executed
    /etc/init.d/o2cb start
    /etc/init.d/ocfs2 start
    /bin/sleep 15
    /etc/init.d/heartbeat start
  ;;
  stop)
    ## commands will be executed
    /etc/init.d/heartbeat stop
    /bin/sleep 15
    /etc/init.d/ocfs2 stop
    /etc/init.d/o2cb stop
  ;;
  *)
    exit 0
  ;;
esac 





