// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class CallTest extends Test {
    public  static variant arguments;
    public  static variant name;
    public  static variant title;
    public  static variant description;
    public  static variant verbatim;
    public  static variant multiline;
    public  static variant default_value;
    public  static variant enumerals;
    public  variant log;
    public  variant ccap;
    public  variant pcap;
    public  variant dbg;
    public  Proc runList = new Proc();
    public void Run() {
    }
    public void killErrantGenProcs() {
    }
    public void assert_() {
    }
    public void assertEquals() {
    }
    public void getCDRCount() {
    }
    public void runCommand() {
    }
    public void stopCommand() {
    }
    public void checkFastSlowStart() {
    }
    public void checkTunneling() {
    }
    public void checkSIPFaxNeg() {
    }
    public void checkH323FaxNeg() {
    }
    public void _stopGens() {
    }
    public void _verifyMedia() {
    }
}
