
/*
*/
// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class CDRTest extends Test {
    public  static variant arguments;
    public  static variant name;
    public  static variant title;
    public  static variant description;
    public  static variant verbatim;
    public  static variant multiline;
    public  static variant default_value;
    public  variant log;
    public void Run() {
    }
    public void assert_() {
    }
    public void assertEquals() {
    }
    public void _stopGens() {
    }
}
