// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class Endpoint extends Resource {
    public  static variant arguments;
    public  static variant name;
    public  static variant title;
    public  static variant not_empty_text;
    public  static variant description;
    public  static variant default_value;
    public  variant log;
    public  variant shell;
    public  variant ostype;
    public  variant network;
    public  variant ipAddr;
    public  variant ethport;
    public void SetUp() {
    }
    public void CleanUp() {
    }
}
