// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class LocalServer extends Resource {
    public  static variant arguments;
    public  static variant name;
    public  static variant title;
    public  static variant not_empty_text;
    public  static variant description;
    public  variant log;
    public void SetUp() {
    }
    public void CleanUp() {
    }
}
