
/*
*/
// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class MetaCallTest extends Test {
    public  static variant arguments;
    public  static variant name;
    public  static variant title;
    public  static variant description;
    public  static variant verbatim;
    public  static variant multiline;
    public  static variant default_value;
    public  static variant enumerals;
    public  variant ccap;
    public  variant pcap;
    public  variant dbg;
    public  variant log;
    public  variant context;
    public  variant metaResult;
    public  Proc runList = new Proc();
    public  Result result = new Result();
    public void __printBanner() {
    }
    public void __preTestChecks() {
    }
    public void __startDataCollectors() {
    }
    public void __stopDataCollectors() {
    }
    public void __executeDataSource() {
    }
    public void __executeTestSource() {
    }
    public void __executeAssertSource() {
    }
    public void __cleanup() {
    }
    public void Run() {
    }
    public void assert_() {
    }
    public void assertEquals() {
    }
    public void getCDRCount() {
    }
    public void runCommand() {
    }
    public void stopCommand() {
    }
    public void _stopGens() {
    }
}
