// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class Realm extends Resource {
    public  static variant arguments;
    public  static variant name;
    public  static variant title;
    public  static variant not_empty_text;
    public  static variant description;
    public  static variant default_value;
    public  variant log;
    public  variant ethport;
    public  variant ipaddr;
    public void SetUp() {
    }
}
