
/*
*/
// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class Resource extends Runnable {
    public  static variant kind;
    public void SetUp() {
    }
    public void CleanUp() {
    }
}
